//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITSAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer_ScoreMappings
    {
        public System.Guid ID { get; set; }
        public System.Guid AnswerID { get; set; }
        public long Value { get; set; }
        public System.Guid OperatorID { get; set; }
        public string DateUnit { get; set; }
    
        public virtual Answer_Operators Answer_Operators { get; set; }
        public virtual Answer Answer { get; set; }
    }
}
