//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITSAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Answer()
        {
            this.Answer_ScoreMappings = new HashSet<Answer_ScoreMappings>();
            this.Result_Answers = new HashSet<Result_Answers>();
            this.Result_Answers_Fixings = new HashSet<Result_Answers_Fixings>();
        }
    
        public System.Guid ID { get; set; }
        public string Description { get; set; }
        public int Score { get; set; }
        public System.Guid QuestionID { get; set; }
        public bool Deleted { get; set; }
        public bool CatchAll { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer_ScoreMappings> Answer_ScoreMappings { get; set; }
        public virtual Question Question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result_Answers> Result_Answers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result_Answers_Fixings> Result_Answers_Fixings { get; set; }
    }
}
