//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITSAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer_Operators
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Answer_Operators()
        {
            this.Answer_ScoreMappings = new HashSet<Answer_ScoreMappings>();
        }
    
        public System.Guid ID { get; set; }
        public string OperatorDescription { get; set; }
        public string Operator { get; set; }
        public int eNumMapping { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer_ScoreMappings> Answer_ScoreMappings { get; set; }
    }
}
