//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITSAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public System.Guid ID { get; set; }
        public string PageName { get; set; }
        public string Icon { get; set; }
        public int DisplayOrder { get; set; }
        public string Link { get; set; }
        public string DisplayName { get; set; }
    }
}
