//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITSAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionGroup_User_Mapping
    {
        public System.Guid MappingID { get; set; }
        public System.Guid GroupID { get; set; }
        public string UserID { get; set; }
    
        public virtual PermissionGroup PermissionGroup { get; set; }
    }
}
