//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITSAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> CalculationModelID { get; set; }
        public Nullable<int> Weighting { get; set; }
        public Nullable<System.Guid> SubCategoryID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool CanBeNA { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.Guid> SubQuestionnaireID { get; set; }
        public bool SubQuestionnaireMultipleTimes { get; set; }
        public Nullable<System.Guid> StalenessProfileID { get; set; }
        public int DefaultValue { get; set; }
        public bool CanBeNotAnswered { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual CalculationModel CalculationModel { get; set; }
        public virtual Questionnaire Questionnaire { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual StalenessProfile StalenessProfile { get; set; }
    }
}
