//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITSAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role_User_PermissionMapping
    {
        public System.Guid PermissionMappingID { get; set; }
        public string ObjectSID { get; set; }
        public Nullable<System.Guid> RoleID { get; set; }
    }
}
