//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITSAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public System.Guid ID { get; set; }
        public string AssignedTo { get; set; }
        public System.DateTime DueDate { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid Status { get; set; }
        public Nullable<System.Guid> ResultLineID { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
    
        public virtual TaskStatu TaskStatu { get; set; }
    }
}
