//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITSAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vFixingResult
    {
        public string Name { get; set; }
        public string RawAnswer { get; set; }
        public Nullable<int> RawScore { get; set; }
        public Nullable<decimal> CalcWeightedScore { get; set; }
        public Nullable<decimal> CalcStalenessScore { get; set; }
        public string Expr1 { get; set; }
        public System.DateTime SelectedDate { get; set; }
    }
}
